SECTION_MAP = {
    "Animals": "I",
    "Vegetables": "II",
    "Oils/Fats": "III",
    "Food/Drink": "IV",
    "Minerals": "V",
    "Chemicals": "VI",
    "Plastics/Rubber": "VII",
    "Leather/Furs": "VIII",
    "Woodwork": "IX",
    "Paper": "X",
    "Textiles": "XI",
    "Footwear/Wearables": "XII",
    "Stone/Ceramics": "XIII",
    "Jewellery": "XIV",
    "Metals": "XV",
    "Machinery/Electronics": "XVI",
    "Transport": "XVII",
    "Instruments": "XVIII",
    "Arms": "XIX",
    "Misc. Goods": "XX",
    "Art/Antiques": "XXI",
}