{
  "header.edn": "EDN  System generated number",
  "header.reference_official_use_only": "1 Reference  OFFICIAL USE ONLY",
  "header.your_reference": "3 Your reference",
  "header.reporting_party.type": "",
  "header.reporting_party.id": "4 Reporting party ID",
  "header.intended_date_of_export": "",
  "header.unique_consignment_reference": "6 Unique consignment reference number",
  "header.customable_excisable_indicator": "",
  "header.prescribed_goods_indicator": "",
  "header.warehouse_establishment_id": "9 Warehouse Est ID",
  "header.goods_owner.party_id": "10 Goods owner party ID ABNCCID",
  "header.goods_owner.branch_id": "11 Branch ID  Confirming export only",
  "header.confirming_exporter_type": "",
  "header.export_goods_type": "",
  "header.mode_of_transport": "",
  "header.vessel_or_flight_id": "20 Vessel ID  Flight number",
  "header.voyage_number": "21 Voyage number",
  "header.total_number_packages": "23 Total number packages",
  "header.total_number_containers": "24 Total number containers",
  "header.invoice_currency": "25 Invoice currency",
  "header.fob_currency": "26 FOB currency",
  "header.total_fob_value": "27 Total FOB value",

  "parties.consignor.name": "",
  "parties.consignor.address": "",
  "parties.consignee.name": "14 Consignee name",
  "parties.consignee.city": "15 Consignee city",
  "parties.consignee.country_code": "",
  "parties.final_destination_country_code": "18 Final destination country code",

  "line_items.0.line_number": "28A Line number",
  "line_items.0.ahecc_code": "28 Commodity Classification code AHECC",
  "line_items.0.goods_description": "",
  "line_items.0.goods_origin.code": "30 Goods origin code",
  "line_items.0.goods_origin.country_codes": "31 Goods origin country codes",
  "line_items.0.temporary_import_number": "32 Temporary import number",
  "line_items.0.net_quantity.amount": "Net Quantity \\) Amount",
  "line_items.0.net_quantity.unit": "",
  "line_items.0.gross_weight.amount": "Gross weight\\) Amount",
  "line_items.0.gross_weight.unit": "",
  "line_items.0.line_fob_value": "35 Line FOB value",
  "line_items.0.permit.prefix": "36 Permit prefix",
  "line_items.0.permit.number": "Permit number",

  "declaration.supplementary_pages_count": "supplementary pages insert number of additional supplementary pages not including notes pages and hereby declare I am the",
  "declaration.declarant_role": "",
  "declaration.entry_maker.name": "Name of the person making the entry",
  "declaration.entry_maker.position": "Position in company",
  "declaration.entry_maker.company_name": "Company name",
  "declaration.entry_maker.contact.address": "Contact address",
  "declaration.entry_maker.contact.phone_number": "Contact phone number",
  "declaration.entry_maker.contact.fax_number": "Contact fax number",
  "declaration.entry_maker.contact.email_address": "Contact email address",
  "declaration.signature": "Signature2_es_:signer:signature",
  "declaration.date_signed": "Date34_es_:signer:date"
}
