from pydantic import BaseModel, Field
from typing import Optional

class B957ExportDeclaration(BaseModel):
    reporting_party_type: str = Field(..., description="Reporting Party Type. Must be 'Owner' or 'Agent'.")
    reporting_party_id: str = Field(..., description="Reporting Party ID. Must be ABN or CCID format.")
    intended_date_of_export: str = Field(..., description="Intended Date of Export. Must be in DD/MM/YYYY format.")
    unique_consignment_reference: Optional[str] = Field(None, description="Unique Consignment Reference. Alphanumeric format.")
    customable_excisable_goods: str = Field(..., description="Customable / Excisable Goods. Must be 'Yes' or 'No'.")
    prescribed_goods: str = Field(..., description="Prescribed Goods. Must be 'Yes' or 'No'.")
    warehouse_establishment_id: Optional[str] = Field(None, description="Warehouse Establishment ID. Required if excisable goods are 'Yes'.")
    goods_owner_party_id: str = Field(..., description="Goods Owner Party ID. Must be ABN or CCID format.")
    goods_owner_party_name: str = Field(..., description="Goods Owner Party Name. Full company or individual name.")
    goods_origin_type: str = Field(..., description="Goods Origin Type. Must be 'Domestic' or 'Overseas'.")
    consignor_name: Optional[str] = Field(None, description="Consignor Name. Name of the party sending the goods.")
    consignor_address: Optional[str] = Field(None, description="Consignor Address. Full address of the consignor.")
    consignee_name: Optional[str] = Field(None, description="Consignee Name. Name of the party receiving the goods.")
    consignee_country_code: str = Field(..., description="Consignee Country Code. Must be ISO Country Code (e.g., 'US', 'AU', 'CN').")
    port_of_loading: str = Field(..., description="Port of Loading. Must be UN/LOCODE or port name.")
    port_of_discharge: Optional[str] = Field(None, description="Port of Discharge. Must be UN/LOCODE or port name.")
    nature_of_the_transaction: str = Field(..., description="Nature of the Transaction. Must be 'Export', 'Repair', or 'Temporary'.")
    cargo_type: str = Field(..., description="Cargo Type. Must be 'FCL', 'LCL', 'Bulk', or 'Air'.")
    cargo_status: str = Field(..., description="Cargo Status. Must be 'Empty' or 'Full'.")
    declared_value: str = Field(..., description="Declared Value. Must be in AUD currency format.")
    terms_of_trade_incoterms: str = Field(..., description="Terms of Trade (Incoterms). Must be standard incoterms like 'EXW', 'FOB', 'CIF', 'DDP'.")
    permit_number: Optional[str] = Field(None, description="Permit Number. Required for controlled goods.")
    permit_issuer_code: Optional[str] = Field(None, description="Permit Issuer Code. Code of the authority that issued the permit.")
    freight_forwarder_name: Optional[str] = Field(None, description="Freight Forwarder Name. Name of the booking agent or freight forwarder.")
    freight_forwarder_abn: Optional[str] = Field(None, description="Freight Forwarder ABN. Australian Business Number of the freight forwarder.")
    ahecc_code: str = Field(..., description="AHECC Code. Must be 8-digit numeric code.")
    line_number: str = Field(..., description="Line Number. Must be numeric. Use '1' for single line exports.")
    goods_description: str = Field(..., description="Goods Description. Detailed description of the goods being exported.")
    origin_country: str = Field(..., description="Origin Country. Must be ISO Country Code of where goods were manufactured.")
    gross_weight_kg: str = Field(..., description="Gross Weight (kg). Must be decimal number in kilograms.")
    net_weight_kg: str = Field(..., description="Net Weight (kg). Must be decimal number in kilograms.")
    quantity: str = Field(..., description="Quantity. Must be decimal number representing total items.")
    unit_of_measure: str = Field(..., description="Unit of Measure. Must be ISO UOM like 'KG', 'LTR', 'NO', 'PCS'.")
    fob_value_aud: str = Field(..., description="FOB Value (AUD). Must be decimal number in Australian dollars.")
    container_number: Optional[str] = Field(None, description="Container Number. Required if cargo type is 'FCL'.") 