form_data = {
    'Import type': '<Enter value for Import type>',
    'Owner Details Owner Name': '<Enter value for Owner Details Owner Name>',
    'Owner ID ABN ABNCAC or CCID': '<Enter value for Owner ID ABN ABNCAC or CCID>',
    'Owner Reference': '<Enter value for Owner Reference>',
    'Biosecurity Inspection Location': '<Enter value for Biosecurity Inspection Location>',
    'Hphone1': '<Enter value for Hphone1>',
    'Hphone2': '<Enter value for Hphone2>',
    'Wphone1': '<Enter value for Wphone1>',
    'Wphone2': '<Enter value for Wphone2>',
    'Mobile': '<Enter value for Mobile>',
    'F1': '<Enter value for F1>',
    'F2': '<Enter value for F2>',
    'Owner email': '<Enter value for Owner email>',
    'Destination Port Code': '<Enter value for Destination Port Code>',
    'Invoice Term Type': '<Enter value for Invoice Term Type>',
    'Valuation Date': '<Enter value for Valuation Date>',
    'Header Valuation Advice No': '<Enter value for Header Valuation Advice No>',
    'EFT': '<Enter value for EFT>',
    'Amount1': '<Enter value for Amount1>',
    'Currency1': '<Enter value for Currency1>',
    'Amount2': '<Enter value for Amount2>',
    'Currency2': '<Enter value for Currency2>',
    'Amount3': '<Enter value for Amount3>',
    'Currency3': '<Enter value for Currency3>',
    'Amount4': '<Enter value for Amount4>',
    'Currency4': '<Enter value for Currency4>',
    'Amount5': '<Enter value for Amount5>',
    'Currency5': '<Enter value for Currency5>',
    'Amount6': '<Enter value for Amount6>',
    'Currency6': '<Enter value for Currency6>',
    'Amount7': '<Enter value for Amount7>',
    'Currency7': '<Enter value for Currency7>',
    'Amount8': '<Enter value for Amount8>',
    'Currency8': '<Enter value for Currency8>',
    'Amount9': '<Enter value for Amount9>',
    'Currency9': '<Enter value for Currency9>',
    'T3': '<Enter value for T3>',
    'T4': '<Enter value for T4>',
    'Declaration': '<Enter value for Declaration>',
    'No': '<Enter value for No>',
    'Date1': '<Enter value for Date1>',
    'Airline Code': '<Enter value for Airline Code>',
    'Loading Port1': '<Enter value for Loading Port1>',
    'First Arrival Port1': '<Enter value for First Arrival Port1>',
    'Discaharge Port1': '<Enter value for Discaharge Port1>',
    'First Arrival Date1': '<Enter value for First Arrival Date1>',
    'Gross Weight1': '<Enter value for Gross Weight1>',
    'Gross Weight Unit1': '<Enter value for Gross Weight Unit1>',
    'Line No1': '<Enter value for Line No1>',
    'Master Air Waybill NoRow1': '<Enter value for Master Air Waybill NoRow1>',
    'House Air Waybill NoRow1': '<Enter value for House Air Waybill NoRow1>',
    'No of Packages1': '<Enter value for No of Packages1>',
    'Marks  Numbers DescriptionRow1': '<Enter value for Marks  Numbers DescriptionRow1>',
    'Line No2': '<Enter value for Line No2>',
    'Master Air Waybill NoRow2': '<Enter value for Master Air Waybill NoRow2>',
    'House Air Waybill NoRow2': '<Enter value for House Air Waybill NoRow2>',
    'No of Packages2': '<Enter value for No of Packages2>',
    'Marks  Numbers DescriptionRow2': '<Enter value for Marks  Numbers DescriptionRow2>',
    'Vessel Name': '<Enter value for Vessel Name>',
    'Vessel ID': '<Enter value for Vessel ID>',
    'Voyage No': '<Enter value for Voyage No>',
    'Loading Port_2': '<Enter value for Loading Port_2>',
    'First arrival1': '<Enter value for First arrival1>',
    'Discharge Port': '<Enter value for Discharge Port>',
    'First Arrival Date_2': '<Enter value for First Arrival Date_2>',
    'Gross Weight_2': '<Enter value for Gross Weight_2>',
    'Gross Weight Unit_2': '<Enter value for Gross Weight Unit_2>',
    'Line No3': '<Enter value for Line No3>',
    'Cargo TypeRow1': '<Enter value for Cargo TypeRow1>',
    'Container NoRow1': '<Enter value for Container NoRow1>',
    'Ocean Bill of Lading No1': '<Enter value for Ocean Bill of Lading No1>',
    'House Bill of Lading No1': '<Enter value for House Bill of Lading No1>',
    'No of Packages3': '<Enter value for No of Packages3>',
    'Marks  Numbers DescriptionRow3': '<Enter value for Marks  Numbers DescriptionRow3>',
    'Line No4': '<Enter value for Line No4>',
    'Cargo TypeRow2': '<Enter value for Cargo TypeRow2>',
    'Container NoRow2': '<Enter value for Container NoRow2>',
    'Ocean Bill of Lading No2': '<Enter value for Ocean Bill of Lading No2>',
    'House Bill of Lading No2': '<Enter value for House Bill of Lading No2>',
    'No of Packages4': '<Enter value for No of Packages4>',
    'Marks  Numbers DescriptionRow4': '<Enter value for Marks  Numbers DescriptionRow4>',
    'Loading Port_3': '<Enter value for Loading Port_3>',
    'First Arrival Port_2': '<Enter value for First Arrival Port_2>',
    'Discharge Port_2': '<Enter value for Discharge Port_2>',
    'DateB1': '<Enter value for DateB1>',
    'MonthB1': '<Enter value for MonthB1>',
    'Yearb1': '<Enter value for Yearb1>',
    'Parcel Post Card Nos': '<Enter value for Parcel Post Card Nos>',
    'Gross Weight_3': '<Enter value for Gross Weight_3>',
    'Gross Weight Unit_3': '<Enter value for Gross Weight Unit_3>',
    'Number of Packages': '<Enter value for Number of Packages>',
    'Marks & Numbers description': '<Enter value for Marks & Numbers description>',
    'Department Receipt for Goods No': '<Enter value for Department Receipt for Goods No>',
    'No of Packages5': '<Enter value for No of Packages5>',
    'Loading Port_4': '<Enter value for Loading Port_4>',
    'First Arrival Port_3': '<Enter value for First Arrival Port_3>',
    'Discharge Port_3': '<Enter value for Discharge Port_3>',
    'First Arrival Date_3': '<Enter value for First Arrival Date_3>',
    'Gross Weight_4': '<Enter value for Gross Weight_4>',
    'Gross Weight Unit_4': '<Enter value for Gross Weight Unit_4>',
    'IMPORTANT Name': '<Enter value for IMPORTANT Name>',
    'Delivery Address': '<Enter value for Delivery Address>',
    'details Locality': '<Enter value for details Locality>',
    'State1': '<Enter value for State1>',
    'Postcode1': '<Enter value for Postcode1>',
    'Contact Phone No': '<Enter value for Contact Phone No>',
    'Line No1C': '<Enter value for Line No1C>',
    'Supplier ID': '<Enter value for Supplier ID>',
    'Vendor ID 1': '<Enter value for Vendor ID 1>',
    'Supplier Name': '<Enter value for Supplier Name>',
    'Tariff Classification No': '<Enter value for Tariff Classification No>',
    'Stat code1': '<Enter value for Stat code1>',
    'Tc1': '<Enter value for Tc1>',
    'Valuation Basis Type1': '<Enter value for Valuation Basis Type1>',
    'Treatment Code1': '<Enter value for Treatment Code1>',
    'GST Exemption Code1': '<Enter value for GST Exemption Code1>',
    'Establishment Code1': '<Enter value for Establishment Code1>',
    'Goods DescriptionC': '<Enter value for Goods DescriptionC>',
    'Quantity1': '<Enter value for Quantity1>',
    'Unit1': '<Enter value for Unit1>',
    'Permit number1': '<Enter value for Permit number1>',
    'AmountC1': '<Enter value for AmountC1>',
    'CurrencyC1': '<Enter value for CurrencyC1>',
    'PriceRow1': '<Enter value for PriceRow1>',
    'AmountC2': '<Enter value for AmountC2>',
    'CurrencyC2': '<Enter value for CurrencyC2>',
    'PriceRow2': '<Enter value for PriceRow2>',
    'AmountC3': '<Enter value for AmountC3>',
    'CurrencyC3': '<Enter value for CurrencyC3>',
    'PriceRow3': '<Enter value for PriceRow3>',
    'AmountC4': '<Enter value for AmountC4>',
    'CurrencyC4': '<Enter value for CurrencyC4>',
    'Origin Country1': '<Enter value for Origin Country1>',
    'Preference Origin Country1': '<Enter value for Preference Origin Country1>',
    'Preference Scheme Type1': '<Enter value for Preference Scheme Type1>',
    'Preference Rule Type1': '<Enter value for Preference Rule Type1>',
    'Instrument Type1': '<Enter value for Instrument Type1>',
    'Instrument Number1': '<Enter value for Instrument Number1>',
    'Instrument Type2': '<Enter value for Instrument Type2>',
    'Instrument Number2': '<Enter value for Instrument Number2>',
    'Additional Information': '<Enter value for Additional Information>',
    'Producer Code': '<Enter value for Producer Code>',
    'Line No1C_2': '<Enter value for Line No1C_2>',
    'Supplier ID_2': '<Enter value for Supplier ID_2>',
    'Vendor ID 1_2': '<Enter value for Vendor ID 1_2>',
    'Supplier Name_2': '<Enter value for Supplier Name_2>',
    'Tariff Classification No_2': '<Enter value for Tariff Classification No_2>',
    'Stat code_2': '<Enter value for Stat code_2>',
    'Tc2': '<Enter value for Tc2>',
    'Valuation Basis Type_2': '<Enter value for Valuation Basis Type_2>',
    'Treatment Code_2': '<Enter value for Treatment Code_2>',
    'GST Exemption Code_2': '<Enter value for GST Exemption Code_2>',
    'Establishment Code2': '<Enter value for Establishment Code2>',
    'Goods DescriptionC_2': '<Enter value for Goods DescriptionC_2>',
    'Quantity_2': '<Enter value for Quantity_2>',
    'Unit_2': '<Enter value for Unit_2>',
    'Permit number2': '<Enter value for Permit number2>',
    'AmountC1_2': '<Enter value for AmountC1_2>',
    'CurrencyC1_2': '<Enter value for CurrencyC1_2>',
    'PriceRow1_2': '<Enter value for PriceRow1_2>',
    'AmountC2_2': '<Enter value for AmountC2_2>',
    'CurrencyC2_2': '<Enter value for CurrencyC2_2>',
    'PriceRow2_2': '<Enter value for PriceRow2_2>',
    'AmountC3_2': '<Enter value for AmountC3_2>',
    'CurrencyC3_2': '<Enter value for CurrencyC3_2>',
    'PriceRow3_2': '<Enter value for PriceRow3_2>',
    'AmountC4_2': '<Enter value for AmountC4_2>',
    'CurrencyC4_2': '<Enter value for CurrencyC4_2>',
    'Origin Country_2': '<Enter value for Origin Country_2>',
    'Preference Origin Country_2': '<Enter value for Preference Origin Country_2>',
    'Preference Scheme Type_2': '<Enter value for Preference Scheme Type_2>',
    'Preference Rule Type_2': '<Enter value for Preference Rule Type_2>',
    'Instrument Type1_2': '<Enter value for Instrument Type1_2>',
    'Instrument Number1_2': '<Enter value for Instrument Number1_2>',
    'Instrument Type2_2': '<Enter value for Instrument Type2_2>',
    'Instrument Number2_2': '<Enter value for Instrument Number2_2>',
    'Additional Information_2': '<Enter value for Additional Information_2>',
    'Producer Code_2': '<Enter value for Producer Code_2>',
}